/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  url: {
    app: string;
    app_assets: string;
    luzzle_assets: string;
    editor: string;
  };
  text: {
    title: string;
    description: string;
  };
  paths: {
    database: string;
  };
  content: {
    block: {
      root: string;
      feed: string;
    };
  };
  pieces: {
    type: string;
    fields: {
      media?: string;
      title: string;
      summary?: string;
      date_consumed: string;
      tags?: string;
      assets?: string[];
    };
    components?: {
      icon?: string;
      opengraph?: string;
    };
  }[];
  theme: {
    light: {
      "colors-primary"?: string;
      "colors-on-primary"?: string;
      "colors-primary-container"?: string;
      "colors-on-primary-container"?: string;
      "colors-secondary"?: string;
      "colors-on-secondary"?: string;
      "colors-secondary-container"?: string;
      "colors-on-secondary-container"?: string;
      "colors-tertiary"?: string;
      "colors-on-tertiary"?: string;
      "colors-tertiary-container"?: string;
      "colors-on-tertiary-container"?: string;
      "colors-error"?: string;
      "colors-on-error"?: string;
      "colors-error-container"?: string;
      "colors-on-error-container"?: string;
      "colors-surface"?: string;
      "colors-surface-dim"?: string;
      "colors-surface-bright"?: string;
      "colors-surface-inverse"?: string;
      "colors-on-surface"?: string;
      "colors-on-surface-variant"?: string;
      "colors-on-surface-inverse"?: string;
      "colors-surface-container-lowest"?: string;
      "colors-surface-container-low"?: string;
      "colors-surface-container"?: string;
      "colors-surface-container-high"?: string;
      "colors-surface-container-highest"?: string;
      "colors-shadow"?: string;
      "colors-outline"?: string;
      "colors-outline-variant"?: string;
    };
    dark: {
      "colors-primary"?: string;
      "colors-on-primary"?: string;
      "colors-primary-container"?: string;
      "colors-on-primary-container"?: string;
      "colors-secondary"?: string;
      "colors-on-secondary"?: string;
      "colors-secondary-container"?: string;
      "colors-on-secondary-container"?: string;
      "colors-tertiary"?: string;
      "colors-on-tertiary"?: string;
      "colors-tertiary-container"?: string;
      "colors-on-tertiary-container"?: string;
      "colors-error"?: string;
      "colors-on-error"?: string;
      "colors-error-container"?: string;
      "colors-on-error-container"?: string;
      "colors-surface"?: string;
      "colors-surface-dim"?: string;
      "colors-surface-bright"?: string;
      "colors-surface-inverse"?: string;
      "colors-on-surface"?: string;
      "colors-on-surface-variant"?: string;
      "colors-on-surface-inverse"?: string;
      "colors-surface-container-lowest"?: string;
      "colors-surface-container-low"?: string;
      "colors-surface-container"?: string;
      "colors-surface-container-high"?: string;
      "colors-surface-container-highest"?: string;
      "colors-shadow"?: string;
      "colors-outline"?: string;
      "colors-outline-variant"?: string;
    };
    globals: {
      "shadows-raised"?: string;
      "font-mono-name"?: string;
      "font-sans-name"?: string;
      "font-sans-url"?: string;
      "font-sans-weight"?: string;
      "font-sizes-xxs"?: string;
      "font-sizes-xs"?: string;
      "font-sizes-small"?: string;
      "font-sizes-normal"?: string;
      "font-sizes-medium"?: string;
      "font-sizes-large"?: string;
      "font-sizes-xl"?: string;
      "font-sizes-xxl"?: string;
      "font-sizes-mobile-responsive-factor"?: string;
      "font-sizes-root"?: string;
      "font-weights-light"?: string;
      "font-weights-normal"?: string;
      "font-weights-medium"?: string;
      "font-weights-semibold"?: string;
      "font-weights-bold"?: string;
      "radii-none"?: string;
      "radii-small"?: string;
      "radii-medium"?: string;
      "radii-large"?: string;
      "radii-xl"?: string;
      "radii-x2l"?: string;
      "radii-x3l"?: string;
      "radii-x4l"?: string;
      "radii-full"?: string;
      "breakpoints-phone"?: string;
      "breakpoints-tablet"?: string;
      "breakpoints-laptop"?: string;
      "breakpoints-desktop"?: string;
      "space-1"?: string;
      "space-2"?: string;
      "space-3"?: string;
      "space-4"?: string;
      "space-5"?: string;
      "space-6"?: string;
      "space-7"?: string;
      "space-8"?: string;
      "space-9"?: string;
      "space-10"?: string;
      "space-0-5"?: string;
      "space-1-5"?: string;
      "space-2-5"?: string;
      "space-3-5"?: string;
    };
  };
}
