#!/usr/bin/env node
// Reads the worker's sidequest.jobs.ts registry and emits a stub registry
// that producers (e.g. explorer) can ship alongside their own bundle.
//
// The stub classes only need matching .name properties — Sidequest's manual
// resolution mode looks up handlers by class name in the consumer's registry.
// Producer-side run() bodies are never invoked.
//
// Usage:
//   node scripts/generate-stubs.js --out <path>
//   node scripts/generate-stubs.js --source <ts-file> --out <path>
//
// Note on Type Safety: The generated stubs are plain classes and do not
// preserve the Job<PayloadType> generics from the source file. This means
// consumers will not get IDE autocomplete or compile-time checks for job payloads.
// If payload shapes become complex, we may need to extract and preserve those
// types in the future.

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const DEFAULT_SOURCE = resolve(SCRIPT_DIR, '../src/sidequest.jobs.ts')

export function extractClassNames(source) {
	const names = new Set()

	// `export { A, B as C } from '...'` and bare `export { A }`
	for (const m of source.matchAll(/export\s*\{([^}]+)\}/g)) {
		for (const part of m[1].split(',')) {
			const trimmed = part.trim()
			if (!trimmed) continue
			const name = trimmed.split(/\s+as\s+/i).pop().trim()
			if (name && /^[A-Z][\w$]*$/.test(name)) names.add(name)
		}
	}

	// `export class X` / `export default class X` / `export abstract class X`
	for (const m of source.matchAll(
		/export\s+(?:default\s+)?(?:abstract\s+)?class\s+([A-Z][\w$]*)/g
	)) {
		names.add(m[1])
	}

	return [...names]
}

export function renderStubFile(names) {
	const lines = [
		'// AUTO-GENERATED by packages/web/worker/scripts/generate-stubs.js.',
		'// Do not edit by hand — re-run the generator instead.',
		"import { Job } from '@sidequest/core'",
		''
	]
	for (const name of names) {
		lines.push(`export class ${name} extends Job {`)
		// Variadic `...args` keeps Sidequest.build(Stub).enqueue(payload) type-checking
		// even though the producer-side run() body is never invoked.
		lines.push(
			`\trun(..._args: unknown[]) { throw new Error('${name}: producer-side stub; runs in worker process') }`
		)
		lines.push('}')
		lines.push('')
	}
	return lines.join('\n')
}

function main() {
	const { values } = parseArgs({
		options: {
			source: { type: 'string' },
			out: { type: 'string' }
		}
	})

	if (!values.out) {
		console.error('error: --out <path> is required')
		process.exit(1)
	}

	const source = values.source ? resolve(values.source) : DEFAULT_SOURCE
	const out = resolve(values.out)

	const text = readFileSync(source, 'utf8')
	const names = extractClassNames(text)

	if (names.length === 0) {
		console.error(`error: no exported classes found in ${source}`)
		process.exit(1)
	}

	mkdirSync(dirname(out), { recursive: true })
	writeFileSync(out, renderStubFile(names))
	console.log(`generate-stubs: wrote ${out} (${names.join(', ')})`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
	main()
}
