#:schema https://fnox.jdx.dev/schema.json

[secrets]
# generate with: openssl rand -hex 32
LUZZLE_AUTH_SECRET = { default = "replace-me-with-a-secret" }
LUZZLE_AUTH_PASSWORD = { default = "luzzle" }
# generate with: openssl rand -hex 32
LUZZLE_BUILDER_TOKEN = { default = "replace-me-with-a-secret" }
GOOGLE_API_KEY= { provider = "seahorse", value = "GOOGLE_API_KEY" }
