pipeline:
  test:
    image: node:16
    commands:
      - npm install
      - npm run test
  deploy:
    image: cr.eleith.com/ci/gcs-web-deploy:latest
    environment:
      - LOG_DIR=gs://eleith-cloud-builds/logs
      - STAGING_DIR=gs://eleith-cloud-builds/eleith-io-site
      - RUN_KEY_FILE=/tmp/secrets/service-account-key.json
      - GCR_IMAGE=gcr.io/eleith-cloud/eleith-io-site
      - GCS_PROJECT=eleith-cloud
      - GCS_REGION=us-central1
      - GCS_SITE_PUBLIC_PATH=eleith-io-site
      - GCS_SITE_PUBLIC_STAGING_PATH=eleith-io-site-dev/main
      - GCS_SITE_DATA_PATH=eleith-io-site-data/main
    commands:
      - mkdir /tmp/secrets
      - mkdir prisma/data
      - touch .env.local
      - eval "echo \"$(cat .env.production)\"" > .env.production
      - echo $${CLOUD_RUN_SERVICE_KEY_JSON} | sed -z 's/\n/\\\n/g' | sed -z 's/\\\n$//g' > $RUN_KEY_FILE
      - gcloud auth activate-service-account --key-file $RUN_KEY_FILE
      - gsutil rsync -d -r gs://eleith-io-site-dev/main gs://eleith-io-site
      - gsutil rsync -r gs://eleith-io-site-data/main prisma/data
      - gcloud builds submit --gcs-source-staging-dir $STAGING_DIR --gcs-log-dir $LOG_DIR --tag $GCR_IMAGE --project=$GCS_PROJECT
      - gcloud run deploy eleith-io-site --image $GCR_IMAGE --platform managed --region $GCS_REGION --project=$GCS_PROJECT
    secrets: [ cloud_run_service_key_json, nextjs_env_host, nextjs_env_public_host_static ]
    when:
      branch: main
  notify:
    image: cr.eleith.com/ci/woodpecker-email:1.0.0
    environment:
      - PLUGIN_FROM_ADDRESS=online-woodpecker@eleith.com
      - PLUGIN_FROM_NAME="eleith ci"
      - PLUGIN_RECIPIENTS_ONLY=true
    secrets:
      - source: smtp_username
        target: plugin_username
      - source: smtp_password
        target: plugin_password
      - source: smtp_host
        target: plugin_host
      - source: smtp_to
        target: plugin_recipients
    when:
      status: [failure, success]
