pipeline:
  test:
    image: node:16
    commands:
      - npm install
      - npm run test
  deploy:
    image: cr.eleith.com/ci/gcs-web-deploy:latest
    environment:
      - LOG_DIR=gs://eleith-cloud-builds/logs
      - STAGING_DIR=gs://eleith-cloud-builds/eleith-io-site
      - RUN_KEY_FILE=/tmp/secrets/service-account-key.json
      - RCLONE_KEY_FILE=/tmp/secrets/rclone-service-key.json
      - GCR_IMAGE=gcr.io/eleith-cloud/eleith-io-site
      - GCS_PROJECT=eleith-cloud
      - GCS_REGION=us-central1
      - GCS_SITE_PUBLIC_PATH=eleith-io-site
      - GCS_SITE_PUBLIC_STAGING_PATH=eleith-io-site-dev/main
      - GCS_SITE_DATA_PATH=eleith-io-site-data/main
    commands:
      - mkdir /tmp/secrets
      - touch .env.local
      - echo $${CLOUD_RUN_SERVICE_KEY_JSON} | sed -z 's/\n/\\\n/g' | sed -z 's/\\\n$//g' > $RUN_KEY_FILE
      - echo $${RCLONE_SERVICE_KEY_JSON} | sed -z 's/\n/\\\n/g' | sed -z 's/\\\n$//g' > $RCLONE_KEY_FILE
      - rclone sync -P --gcs-service-account-file=$RCLONE_KEY_FILE --gcs-location=$GCS_REGION --gcs-storage-class="REGIONAL" --gcs-project-number=$GCS_PROJECT --gcs-bucket-policy-only=true :gcs:$GCS_SITE_DATA_PATH ./prisma/data
      - rclone sync -P --gcs-service-account-file=$RCLONE_KEY_FILE --gcs-location=$GCS_REGION --gcs-storage-class="REGIONAL" --gcs-project-number=$GCS_PROJECT --gcs-bucket-policy-only=true :gcs:$GCS_SITE_PUBLIC_STAGING_PATH :gcs:$GCS_SITE_PUBLIC_PATH
      - gcloud auth activate-service-account --key-file $RUN_KEY_FILE
      - gcloud builds submit --gcs-source-staging-dir $STAGING_DIR --gcs-log-dir $LOG_DIR --tag $GCR_IMAGE --project=$GCS_PROJECT
      - gcloud run deploy eleith-io-site --image $GCR_IMAGE --platform managed --region $GCS_REGION --project=$GCS_PROJECT
    secrets: [ cloud_run_service_key_json, rclone_service_key_json, nextjs_env_host, nextjs_env_public_host_static ]
    when:
      branch: main
