packages:
  - packages/cli
  - packages/core
  - packages/lsp
  - packages/web/explorer
  - packages/web/config
  - packages/web/worker
  - packages/web/lsp
  - packages/web/proxy
  - packages/web/tools
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
