packages:
  - packages/cli
  - packages/core
  - packages/lsp
  - packages/web/explorer
  - packages/web/config
  - packages/web/theme
  - packages/web/worker
  - packages/web/lsp
  - packages/web/proxy
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
catalog:
  '@eslint/js': 9.22.0
  '@types/eslint': 9.6.1
  '@types/node': 22.12.0
  '@vitest/coverage-v8': 3.2.4
  eslint: 9.22.0
  eslint-config-prettier: 9.1.0
  globals: 16.0.0
  prettier: 3.4.2
  typescript: 5.7.3
  typescript-eslint: 8.19.1
  vite: 7.1.7
  vitest: 3.2.4
