services:
  luzzle-web:
    build:
      dockerfile: Dockerfile
      secrets:
        - npmrc
      context: .
    container_name: luzzle-web
    user: "${UID:-1000}:${GID:-1000}"
    env_file: .env
    environment:
      - LUZZLE_APP_URL=${LUZZLE_APP_URL}
      - LUZZLE_AUTH_SECRET=${LUZZLE_AUTH_SECRET}  # generate by `openssl rand -hex 32`
      - LUZZLE_AUTH_USERNAME=${LUZZLE_AUTH_USERNAME}
      - LUZZLE_AUTH_PASSWORD=${LUZZLE_AUTH_PASSWORD}
      - LUZZLE_BUILD_TOKEN=${LUZZLE_BUILD_TOKEN} # generate by `openssl rand -hex 32`
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./demo/assets/pieces:/app/assets/pieces
      - ./demo/config.yaml:/app/config.yaml
      - ./demo/data:/app/data
      - ./demo/content:/app/content
      - ./demo/archive:/app/archive
    networks:
      - luzzle
    depends_on:
      - luzzle-builder

  luzzle-builder:
    build:
      dockerfile: ../builder/Dockerfile
      secrets:
        - npmrc
      context: ../builder
    container_name: luzzle-builder
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - '9000:9000'
    env_file: .env
    environment:
      - LUZZLE_BUILD_TOKEN=${LUZZLE_BUILD_TOKEN}
      - LUZZLE_APP_URL=${LUZZLE_APP_URL:-http://luzzle-web:3000}
      - LUZZLE_AUTH_USERNAME=${LUZZLE_AUTH_USERNAME}
      - LUZZLE_AUTH_PASSWORD=${LUZZLE_AUTH_PASSWORD}
    networks:
      - luzzle
    volumes:
      - ./demo/config.yaml:/app/config.yaml
      - ./demo/assets:/app/assets
      - ./demo/data:/app/data
      - ./demo/archive:/app/archive

  luzzle-lsp:
    build:
      dockerfile: ../lsp/Dockerfile
      secrets:
        - npmrc
      context: ../lsp
    container_name: luzzle-lsp
    user: '${UID:-1000}:${GID:-1000}'
    networks:
      - luzzle
    ports:
      - '9001:9001'
    volumes:
      - ./demo/archive:/app/archive

  luzzle-proxy:
    build:
      dockerfile: ../proxy/Dockerfile
      secrets:
        - npmrc
      context: ../proxy
    container_name: luzzle-lsp
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      - LUZZLE_EXPLORER_HOST=luzzle-web
      - LUZZLE_EXPLORER_PORT=3000
      - LUZZLE_LSP_HOST=luzzle-lsp
      - LUZZLE_LSP_PORT=9001
    ports:
      - "8080:8080"
    networks:
      - luzzle
    volumes:
      - ./nginx/cache:/tmp/cache
      - ./nginx/logs:/tmp/logs
    depends_on:
      - luzzle-web

secrets:
  npmrc:
    file: $HOME/.npmrc

networks:
  luzzle:
    driver: bridge
e
