services:
  luzzle-dev-web:
    build:
      dockerfile: Dockerfile.dev
      context: .
      additional_contexts:
        core: ../../core
        utils: ../utils
        tools: ../tools
    container_name: luzzle-dev-web
    user: '${UID:-1000}:${GID:-1000}'
    env_file: .env
    environment:
      - LUZZLE_APP_URL=${LUZZLE_APP_URL:-http://localhost:8080}
      - LUZZLE_WEB_HOST=${LUZZLE_WEB_HOST:-luzzle-dev-web}
      - LUZZLE_AUTH_SECRET=${LUZZLE_AUTH_SECRET:-l1k2j3l1k2j312lk3j21lk3jsdflkjou} # generate by `openssl rand -hex 32`
      - LUZZLE_BUILD_TOKEN=${LUZZLE_BUILD_TOKEN:-223lk4j23oi4u23l4jlkj2l3kj4xyewr} # generate by `openssl rand -hex 32`
      - LUZZLE_AUTH_USERNAME=${LUZZLE_AUTH_USERNAME:-admin}
      - LUZZLE_AUTH_PASSWORD=${LUZZLE_AUTH_PASSWORD:-luzzle}
      - LUZZLE_HMR_PORT=8080
      - LUZZLE_DEV=true
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - '5173:5173'
    volumes:
      - ./demo/assets/pieces:/app/assets/pieces
      - ./demo/config.yaml:/app/config.yaml
      - ./demo/data:/app/data
      - ./demo/content:/app/content
      - ./demo/archive:/app/archive
      - ./src:/app/src
      - ./static:/app/static
      - ./scripts:/app/scripts
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.js:/app/svelte.config.js
      - ./vite.config.ts:/app/vite.config.ts
    networks:
      - luzzle
    depends_on:
      - luzzle-dev-builder
      - luzzle-dev-lsp

  luzzle-dev-builder:
    build:
      dockerfile: Dockerfile.dev
      context: ../builder
      additional_contexts:
        core: ../../core
        utils: ../utils
        tools: ../tools
    container_name: luzzle-dev-builder
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - '9000:9000'
    env_file: .env
    environment:
      - LUZZLE_APP_URL=${LUZZLE_APP_URL:-http://luzzle-dev-web:5173}
      - LUZZLE_BUILD_TOKEN=${LUZZLE_BUILD_TOKEN:-223lk4j23oi4u23l4jlkj2l3kj4xyewr} # generate by `openssl rand -hex 32`
      - LUZZLE_AUTH_USERNAME=${LUZZLE_AUTH_USERNAME:-admin}
      - LUZZLE_AUTH_PASSWORD=${LUZZLE_AUTH_PASSWORD:-luzzle}
    networks:
      - luzzle
    volumes:
      - ./demo/config.yaml:/app/config.yaml
      - ./demo/assets:/app/assets
      - ./demo/data:/app/data
      - ./demo/archive:/app/archive
      - ../builder/server.js:/app/server.js
      - ../builder/scripts:/app/scripts

  luzzle-dev-lsp:
    build:
      dockerfile: Dockerfile.dev
      context: ../lsp
      additional_contexts:
        lsp: ../../lsp
    container_name: luzzle-dev-lsp
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - '9001:9001'
    networks:
      - luzzle
    volumes:
      - ./demo/archive:/app/archive
      - ../lsp/server.js:/app/server.js
      - ../lsp/luzzle-lsp.js:/app/luzzle-lsp.js
      - ../lsp/markdownlint-lsp.js:/app/markdownlint-lsp.js

  luzzle-dev-proxy:
    build:
      dockerfile: ../proxy/Dockerfile
      context: ../proxy
    container_name: luzzle-dev-proxy
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      - LUZZLE_EXPLORER_HOST=luzzle-dev-web
      - LUZZLE_EXPLORER_PORT=5173
      - LUZZLE_LSP_HOST=luzzle-dev-lsp
      - LUZZLE_LSP_PORT=9001
      - LUZZLE_PROXY_CACHE=off
      - LUZZLE_PROXY_ACCESS_LOG=/tmp/logs/access.log
      - LUZZLE_PROXY_ERROR_LOG=/tmp/logs/error.log
    ports:
      - '8080:8080'
    networks:
      - luzzle
    volumes:
      - ./nginx/cache:/tmp/cache
      - ./nginx/logs:/tmp/logs
    depends_on:
      - luzzle-dev-web
      - luzzle-dev-lsp

volumes:
  rclone_workdir_dev:

networks:
  luzzle:
    driver: bridge
volumes:
      - ./nginx/cache:/tmp/cache
      - ./nginx/logs:/tmp/logs
    depends_on:
      - luzzle-dev-web
      - luzzle-dev-lsp

networks:
  luzzle:
    driver: bridge
