const ASSETS_DIRECTORY = '.assets'
const DATABASE_PATH = 'luzzle.sqlite'
const LUZZLE_DIRECTORY = '.luzzle'
const LUZZLE_SCHEMAS_DIRECTORY = 'schemas'

export { ASSETS_DIRECTORY, DATABASE_PATH, LUZZLE_DIRECTORY, LUZZLE_SCHEMAS_DIRECTORY }
