// AUTO-GENERATED by packages/web/worker/scripts/generate-stubs.js.
// Do not edit by hand — re-run the generator instead.
import { Job } from '@sidequest/core'

export class Publish extends Job {
	run() {
		throw new Error('Publish: producer-side stub; runs in worker process')
	}
}
