workspace:
  base: /workspace
  path: src

when:
  - event: [push]
    branch: main
    path:
      include:
        - ".woodpecker/.cli.yml"
        - "apps/cli/**"
        - "apps/core/**"
  - event: pull_request
    path:
      include:
        - ".woodpecker/.cli.yml"
        - "apps/cli/**"
        - "apps/core/**"
  - event: tag
    ref: "refs/tags/@luzzle/cli@*"

steps:
  prepare:
    image: node:26
    environment:
      COREPACK_HOME: /workspace/src/.corepack
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - corepack prepare pnpm@11.2.2 --activate
      - pnpm config set store-dir .pnpm-store
      - pnpm install --frozen-lockfile

  build:
    image: node:26
    environment:
      COREPACK_HOME: /workspace/src/.corepack
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - pnpm --filter @luzzle/core build
      - pnpm --filter @luzzle/cli build

  test:
    image: node:26
    environment:
      COREPACK_HOME: /workspace/src/.corepack
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - pnpm --filter @luzzle/cli lint
      - pnpm --filter @luzzle/cli test

  check-version:
    image: node:26
    commands:
      - cd apps/cli
      - |
        VERSION_FROM_PKG=$(node -p "require('./package.json').version")

        if [ "$VERSION_FROM_TAG" != "$VERSION_FROM_PKG" ]; then
          echo "Version mismatch: Git tag version $VERSION_FROM_TAG does not match package.json version: $VERSION_FROM_PKG"
          exit 1
        fi
    environment:
      VERSION_FROM_TAG: "${CI_COMMIT_TAG#@luzzle/cli@}"
    when:
      - event: tag

  publish:
    image: node:26
    environment:
      COREPACK_HOME: /workspace/src/.corepack
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm install --global corepack@latest
      - corepack enable
      - pnpm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - pnpm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - pnpm --filter @luzzle/cli publish --no-git-checks
    when:
      - event: tag

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - event: [push, tag]
        status: [success]

  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - event: [push, tag]
        status: [failure]
