workspace:
  base: /workspace
  path: src

when:
  - event: [push]
    branch: main
    path:
      include:
        - ".woodpecker/.core.yml"
        - "packages/core/**"
  - event: tag
    ref: "refs/tags/core/v*"

steps:
  prepare:
    image: node:24
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  build:
    image: node:24
    commands:
      - corepack enable
      - pnpm --filter @luzzle/core lint
      - pnpm --filter @luzzle/core build

  test:
    image: node:24
    commands:
      - corepack enable
      - pnpm --filter @luzzle/core test

  check-version:
    image: node:24
    commands:
      - cd packages/core
      - |
        VERSION_FROM_PKG=$(node -p "require('./package.json').version")

        if [ "$VERSION_FROM_TAG" != "$VERSION_FROM_PKG" ]; then
          echo "Version mismatch: Git tag version $VERSION_FROM_TAG does not match package.json version: $VERSION_FROM_PKG"
          exit 1
        fi
    environment:
      VERSION_FROM_TAG: ${CI_COMMIT_TAG#core/v}
    when:
      - event: tag

  publish:
    image: node:24
    commands:
      - corepack enable
      - pnpm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - pnpm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - pnpm --filter @luzzle/core publish --no-git-checks
    when:
      - event: tag
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]

  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
