workspace:
  base: /workspace
  path: src

when:
  - event: [push]
    branch: main
    path:
      include: [".woodpecker/.core.yml", "packages/core/**"]
  - event: tag
    ref: "refs/tags/core/v*"

steps:
  build:
    image: node:22
    commands:
      - npm ci -w @luzzle/core -w @luzzle/cli
      - npm run lint -w @luzzle/core
      - npm run build -w @luzzle/core
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token
  test:
    image: node:22
    commands:
      - npm run test -w @luzzle/core
  publish:
    image: node:22
    commands:
      - npm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - npm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - npm run check:version -w @luzzle/core
      - npm publish -w @luzzle/core
    when:
      - event: tag
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token
  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
