workspace:
  base: /workspace
  path: src
steps:
  build:
    image: node:20
    commands:
      - npm ci -w @luzzle/core -w @luzzle/cli
      - npm run lint -w @luzzle/core
      - npm run build -w @luzzle/core
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token
    when:
      - event: [push]
        branch: [main]
        path:
          include: [".woodpecker/.core.yml", "packages/core/**"]
  test:
    image: node:20
    commands:
      - npm run test -w @luzzle/core
    when:
      - event: [push]
        branch: [main]
        path:
          include: [".woodpecker/.core.yml", "packages/core/**"]
  publish:
    image: node:20
    commands:
      - npm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - npm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - cd packages/core
      - NPM_CURRENT_VERSION="$(npm pkg get version --workspaces=false)"
      - NPM_LATEST_VERSION="$(npm show . version --workspaces=false)"
      - cd ../..
      - if test $NPM_CURRENT_VERSION != \"$NPM_LATEST_VERSION\" ; then npm publish -w @luzzle/core; fi
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token
    when:
      - event: [push]
        branch: [main]
        path:
          include: [".woodpecker/.core.yml", "packages/core/**"]
  notify:
    image: deblan/woodpecker-email:2.0.4
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [main]
        path:
          include: [".woodpecker/.core.yml", "packages/core/**"]
