workspace:
  base: /workspace
  path: src
pipeline:
  build:
    image: node:16
    commands:
      - npm ci -w @luzzle/ui
      - npm run compile -w @luzzle/ui
    when:
      branch: [main]
      path:
        include: [".woodpecker/.ui.yml", "packages/ui/**"]
  test:
    image: node:16
    commands:
      - npm run lint -w @luzzle/ui
    when:
      branch: [main]
      path:
        include: [".woodpecker/.ui.yml", "packages/ui/**"]
  publish:
    image: node:16
    commands:
      - npm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - npm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - cd packages/ui
      - NPM_CURRENT_VERSION="$(npm pkg get version --workspaces=false)"
      - NPM_LATEST_VERSION="$(npm show . version --workspaces=false)"
      - cd ../..
      - if test $NPM_CURRENT_VERSION != \"$NPM_LATEST_VERSION\" ; then npm publish -w @luzzle/ui; fi
    secrets: [npm_owner, npm_token]
    when:
      branch: [main]
      path:
        include: [".woodpecker/.ui.yml", "packages/ui/**"]
  notify:
    image: git.eleith.com/eleith/woodpecker-email:1.0.0
    environment:
      - PLUGIN_FROM_ADDRESS=online-woodpecker@eleith.com
      - PLUGIN_FROM_NAME="eleith ci"
      - PLUGIN_RECIPIENTS_ONLY=true
    secrets:
      - source: smtp_username
        target: plugin_username
      - source: smtp_password
        target: plugin_password
      - source: smtp_host
        target: plugin_host
      - source: smtp_to
        target: plugin_recipients
    when:
      status: [failure, success]
      branch: [main]
      path:
        include: [".woodpecker/.ui.yml", "packages/ui/**"]
