workspace:
  base: /workspace
  path: src/website
pipeline:
  build:
    image: node:16
    commands:
      - npm ci -w @luzzle/web -w @luzzle/cli
      - npm run prebuild -w @luzzle/web
      - npm run build -w @luzzle/cli
    when:
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
  test:
    image: node:16
    commands:
      - npm run lint -w @luzzle/web
      - npm run compile -w @luzzle/web
    when:
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
  gather:
    image: rclone/rclone:1.57
    environment:
      - RCLONE_GCS_STORAGE_CLASS=REGIONAL
      - RCLONE_GCS_BUCKET_POLICY_ONLY=true
      - RCLONE_GCS_LOCATION=us-central-1
      - RCLONE_GCS_SERVICE_ACCOUNT_FILE=/tmp/rclone-service-key.json
      - RCLONE_GCS_DB=:gcs:eleith-io-site-data/main/sqlite.dev.db
      - RCLONE_DAV_BOOK_SOURCE=:webdav:documents/eleith/notes-md/personal/records/books
      - RCLONE_DAV_BOOK_DESTINATION=/workspace/data/books
    commands:
      - mkdir /workspace/data
      - mkdir /workspace/data/books
      - cd packages/web
      - mkdir prisma/data
      - echo $${RCLONE_SERVICE_KEY_JSON} > $RCLONE_GCS_SERVICE_ACCOUNT_FILE
      - sed -i ':a;N;$!ba;s/\n/\\\n/g' $RCLONE_GCS_SERVICE_ACCOUNT_FILE
      - rclone copy $RCLONE_DAV_BOOK_SOURCE $RCLONE_DAV_BOOK_DESTINATION
      - rclone copy $RCLONE_GCS_DB prisma/data
    secrets: [rclone_webdav_url, rclone_webdav_vendor, rclone_webdav_user, rclone_webdav_pass, rclone_service_key_json, rclone_gcs_project_number]
    when:
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
  build-content:
    image: node:16
    commands:
      - npm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - npm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - npm run build:prisma -w @luzzle/web
      - npm install -g @luzzle/cli@0.0.7
      - cd packages/web
      - ../cli/dist/manager.js sync /workspace/data/books
      - mkdir public/images
      - cp -R /workspace/data/books/.assets/covers public/images
    secrets: [npm_owner, npm_token]
    when:
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
  deploy:
    image: git.eleith.com/eleith/gcs-web-deploy:3.0.0
    environment:
      - LOG_DIR=gs://eleith-cloud-builds/logs
      - STAGING_DIR=gs://eleith-cloud-builds/eleith-io-site
      - RUN_KEY_FILE=/tmp/secrets/service-account-key.json
      - ENV_LOCAL_FILE=.env.local
      - GCR_IMAGE=gcr.io/eleith-cloud/eleith-io-site
      - GCS_PROJECT=eleith-cloud
      - GCS_REGION=us-central1
    commands:
      - cd packages/web
      - mkdir /tmp/secrets
      - printf '%s\n' "$NEXTJS_ENV_LOCAL" > $ENV_LOCAL_FILE
      - echo $${CLOUD_RUN_SERVICE_KEY_JSON} > $RUN_KEY_FILE
      - sed -i ':a;N;$!ba;s/\n/\\\n/g' $RUN_KEY_FILE
      - gcloud auth activate-service-account --key-file $RUN_KEY_FILE
      - gsutil -m rsync -d -r public gs://eleith-io-site
      - gsutil -m rsync -d -r prisma/data gs://eleith-io-site-data/main
      - gcloud builds submit --gcs-source-staging-dir $STAGING_DIR --gcs-log-dir $LOG_DIR --tag $GCR_IMAGE --project=$GCS_PROJECT
      - gcloud run deploy eleith-io-site --image $GCR_IMAGE --platform managed --region $GCS_REGION --project=$GCS_PROJECT
    secrets: [cloud_run_service_key_json, nextjs_env_local]
    when:
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
  notify:
    image: git.eleith.com/eleith/woodpecker-email:1.0.0
    environment:
      - PLUGIN_FROM_ADDRESS=online-woodpecker@eleith.com
      - PLUGIN_FROM_NAME="eleith ci"
      - PLUGIN_RECIPIENTS_ONLY=true
    secrets:
      - source: smtp_username
        target: plugin_username
      - source: smtp_password
        target: plugin_password
      - source: smtp_host
        target: plugin_host
      - source: smtp_to
        target: plugin_recipients
    when:
      status: [failure, success]
      branch: [main, introduce-monorepo]
      path:
        include: [".woodpecker/.web.yml", "packages/web/*"]
