workspace:
  base: /workspace
  path: src

when:
  - event: [push]
    branch: main
    path:
      include: [".woodpecker/.tools.yml", "packages/web/tools/**"]
  - event: tag
    ref: "refs/tags/web.tools/v*"

steps:
  build:
    image: node:22
    commands:
      - npm ci -w @luzzle/core -w @luzzle/web.utils -w @luzzle/web.tools
      - npm run build -w @luzzle/core -w @luzzle/web.utils
      - npm run build -w @luzzle/web.tools

  test:
    image: node:22
    commands:
      - npm run lint -w @luzzle/web.tools
      - npm run test -w @luzzle/web.tools

  check-version:
    image: node:22
    commands:
      - cd packages/web/tools
      - |
        VERSION_FROM_PKG=$(npm pkg get version --workspaces=false)

        if [ "\"$VERSION_FROM_TAG\"" != "$VERSION_FROM_PKG" ]; then
          echo "Version mismatch: Git tag version "$VERSION_FROM_TAG" does not match package.json version: $VERSION_FROM_PKG"
          exit 1
        fi
    environment:
     VERSION_FROM_TAG: ${CI_COMMIT_TAG#web.tools/v}
    when:
      - event: tag

  publish:
    image: node:22
    commands:
      - npm config set @luzzle:registry https://git.eleith.com/api/packages/$NPM_OWNER/npm/
      - npm config set -- "//git.eleith.com/api/packages/$NPM_OWNER/npm/:_authToken" "$NPM_TOKEN"
      - npm publish -w @luzzle/web.tools
    when:
      - event: tag
    environment:
      NPM_OWNER:
        from_secret: npm_owner
      NPM_TOKEN:
        from_secret: npm_token

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]

  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
