workspace:
  base: /workspace
  path: src
pipeline:
  build:
    image: node:18
    commands:
      - npm ci -w @luzzle/web -w @luzzle/ui -w @luzzle/kysely
      - npm run build -w @luzzle/kysely
      - npm run build:graphql -w @luzzle/web
      - npm run compile -w @luzzle/web
    when:
      branch: [main]
      path:
        include: ["Dockerfile", ".woodpecker/.web.yml", "packages/web/**"]
  test:
    image: node:18
    commands:
      - npm run lint -w @luzzle/web
    when:
      branch: [main]
      path:
        include: [".woodpecker/.web.yml", "packages/web/**"]
  gather:
    image: rclone/rclone:1.57
    environment:
      - RCLONE_GCS_STORAGE_CLASS=REGIONAL
      - RCLONE_GCS_BUCKET_POLICY_ONLY=true
      - RCLONE_GCS_LOCATION=us-central-1
      - RCLONE_GCS_SERVICE_ACCOUNT_FILE=/tmp/rclone-service-key.json
      - RCLONE_DAV_BOOK_SOURCE=:webdav:documents/eleith/notes-md/personal/records
      - RCLONE_DAV_BOOK_DESTINATION=/workspace/data
    commands:
      - mkdir /workspace/data
      - echo $${RCLONE_SERVICE_KEY_JSON} > $RCLONE_GCS_SERVICE_ACCOUNT_FILE
      - sed -i ':a;N;$!ba;s/\n/\\\n/g' $RCLONE_GCS_SERVICE_ACCOUNT_FILE
      - rclone copy $RCLONE_DAV_BOOK_SOURCE $RCLONE_DAV_BOOK_DESTINATION
    secrets:
      [
        rclone_webdav_url,
        rclone_webdav_vendor,
        rclone_webdav_user,
        rclone_webdav_pass,
        rclone_service_key_json,
        rclone_gcs_project_number,
      ]
    when:
      branch: [main]
      path:
        include: ["Dockerfile", ".woodpecker/.web.yml", "packages/web/**"]
  build-content:
    image: node:18
    commands:
      - cd packages/web
      - mkdir public/images
      - mkdir data
      - cp -R /workspace/data/books/.assets/covers public/images
      - cp /workspace/data/luzzle.sqlite data
    when:
      branch: [main]
      path:
        include: ["Dockerfile", ".woodpecker/.web.yml", "packages/web/**"]
  deploy:
    image: git.eleith.com/eleith/gcs-web-deploy:3.0.0
    environment:
      - LOG_DIR=gs://eleith-cloud-builds/logs
      - STAGING_DIR=gs://eleith-cloud-builds/eleith-io-site
      - RUN_KEY_FILE=/tmp/secrets/service-account-key.json
      - ENV_LOCAL_FILE=.env.local
      - GCR_IMAGE=gcr.io/eleith-cloud/eleith-io-site
      - GCS_PROJECT=eleith-cloud
      - GCS_REGION=us-central1
    commands:
      - mkdir /tmp/secrets
      - printf '%s\n' "$NEXTJS_ENV_LOCAL" > ./packages/web/$ENV_LOCAL_FILE
      - echo $${CLOUD_RUN_SERVICE_KEY_JSON} > $RUN_KEY_FILE
      - sed -i ':a;N;$!ba;s/\n/\\\n/g' $RUN_KEY_FILE
      - gcloud auth activate-service-account --key-file $RUN_KEY_FILE
      - gsutil -m rsync -d -r ./packages/web/public gs://eleith-io-site
      - gcloud builds submit --gcs-source-staging-dir $STAGING_DIR --gcs-log-dir $LOG_DIR --tag $GCR_IMAGE --project=$GCS_PROJECT
      - gcloud run deploy eleith-io-site --image $GCR_IMAGE --platform managed --region $GCS_REGION --project=$GCS_PROJECT
    secrets: [cloud_run_service_key_json, nextjs_env_local]
    when:
      branch: [main]
      path:
        include: ["Dockerfile", ".woodpecker/.web.yml", "packages/web/**"]
  notify:
    image: deblan/woodpecker-email:1.0.0-wp
    secrets:
      [
        smtp_notification_from,
        smtp_notification_host,
        smtp_notification_password,
        smtp_notification_from,
        smtp_notification_recipient,
      ]
    settings:
      from:
        from_secret: smtp_notification_from
      host:
        from_secret: smtp_notification_host
      password:
        from_secret: smtp_notification_password
      username:
        from_secret: smtp_notification_username
      recipients:
        from_secret: smtp_notification_recipient
    when:
      event: [push]
      status: [failure, success]
      branch: [main]
      path:
        include: ["Dockerfile", ".woodpecker/.web.yml", "packages/web/**"]
