workspace:
  base: /workspace
  path: src
steps:
  prepare:
    image: node:14
    commands:
      - echo $LUZZLE_NPMRC >> .npmrc
    environment:
      LUZZLE_NPMRC:
        from_secret: luzzle_npmrc
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [main]
        path:
          include: [".woodpecker/.web.yml", "packages/web/**"]
  build_docker:
    image: woodpeckerci/plugin-docker-buildx:pull_186
    settings:
      repo: git.eleith.com/eleith/luzzle
      username: eleith
      dockerfile: packages/web/Dockerfile
      context: packages/web
      registry: https://git.eleith.com
      secrets:
        - id=npmrc\\,src=.npmrc
      auto_tag: true
      password:
        from_secret: gitea_docker_registry
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [main]
        path:
          include: [".woodpecker/.web.yml", "packages/web/**"]
  notify:
    image: deblan/woodpecker-email:2.0.4
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [main]
        path:
          include: [".woodpecker/.web.yml", "packages/web/**"]
