workspace:
  base: /workspace
  path: src
steps:
  build_docker:
    image: woodpeckerci/plugin-docker-buildx:5.0.0
    settings:
      repo: git.eleith.com/eleith/eleith
      username: eleith
      dockerfile: packages/web/Dockerfile
      context: packages/web
      registry: https://git.eleith.com
      secrets:
        from_secret: npm_token
      auto_tag: true
      password:
        from_secret: gitea_docker_registry
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [never_main]
  notify:
    image: deblan/woodpecker-email:2.0.4
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
    when:
      - event: [push, manual]
        status: [failure, success]
        branch: [never_main]
        path:
          include: [".woodpecker/.web.yml", "packages/web/**"]
