workspace:
  base: /workspace
  path: src

when:
  - event: [push]
    branch: [main]
    path:
      include: [".woodpecker/.web-editor.yml", "packages/web/editor/**"]

steps:
  prepare:
    image: node:22
    commands:
      - printf '%s' "$LUZZLE_NPMRC" | sed 's/[[:space:]]*$//' >> /root/.npmrc
      - cd packages/web/editor
      - npm run build:lock
      - npm ci --workspaces=false
    environment:
      LUZZLE_NPMRC:
        from_secret: luzzle_npmrc

  lint:
    image: node:22
    commands:
      - cd packages/web/editor
      - cp .env.sample .env.local
      - npm run lint
      - npm run check

  build_docker:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/luzzle-editor
      username: eleith
      dockerfile: packages/web/editor/Dockerfile
      context: packages/web/editor
      registry: https://git.eleith.com
      build_args:
        secret: id=npmrc,src=.npmrc
      auto_tag: true
      password:
        from_secret: gitea_docker_registry

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]

  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
