workspace:
  base: /workspace
  path: src

when:
  - event: [push, manual, tag]
    branch: [main]
    path:
      include: [".woodpecker/.web-explorer.yml", "packages/web/explorer/**"]

steps:
  prepare:
    image: node:20
    commands:
      - printf '%s' "$LUZZLE_NPMRC" | sed 's/[[:space:]]*$//' >> /root/.npmrc
      - cd packages/web/explorer
      - npm run build:lock
      - npm ci --workspaces=false
      - npm run --silent tag > .tags
    environment:
      LUZZLE_NPMRC:
        from_secret: luzzle_npmrc
  lint:
    image: node:20
    commands:
      - cd packages/web/explorer
      - npm run lint
      - npm run check:config
      - npm run check
  build_docker:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: git.eleith.com/eleith/luzzle-explorer
      username: eleith
      dockerfile: packages/web/explorer/Dockerfile
      context: packages/web/explorer
      registry: https://git.eleith.com
      build_args:
        secret: id=npmrc,src=.npmrc
      tags_file: packages/web/explorer/.tags
      password:
        from_secret: gitea_docker_registry
  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
