workspace:
  base: /workspace
  path: app

when:
  - event: push
    branch: main
    path:
      include: [".woodpecker/.web-builder.yml", "packages/web/builder/**"]
  - event: tag
    ref: "refs/tags/web.builder/v*.*.*"

steps:
  prepare:
    image: node:22
    commands:
      - printf '%s' "$LUZZLE_NPMRC" | sed 's/[[:space:]]*$//' >> /root/.npmrc
    environment:
      LUZZLE_NPMRC:
        from_secret: luzzle_npmrc

  test:
    image: node:22
    commands:
      - npm ci -w @luzzle/web.builder
      - npm run lint -w @luzzle/web.builder
      - npm run test -w @luzzle/web.builder

  extract-semver-tags:
    image: alpine/git:latest
    commands:
      - |
        VERSION_FULL="${CI_COMMIT_TAG#web.builder/v}"
        VERSION_MAJOR=$(echo "$VERSION_FULL" | cut -d. -f1)
        VERSION_MINOR=$(echo "$VERSION_FULL" | cut -d. -f2)

        SEMVER_FULL="$VERSION_FULL"
        SEMVER_MAJOR_MINOR="$VERSION_MAJOR.$VERSION_MINOR"
        SEMVER_MAJOR="$VERSION_MAJOR"

        echo "Extracted versions: $SEMVER_FULL, $SEMVER_MAJOR_MINOR, $SEMVER_MAJOR, "
        echo -e "$SEMVER_FULL\n$SEMVER_MAJOR\n$SEMVER_MAJOR_MINOR" >> .tags
        cat .tags
    when:
      - event: tag

  build-docker-main:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/luzzle-web-builder
      username: eleith
      dockerfile: packages/web/builder/Dockerfile
      registry: https://git.eleith.com
      build_args:
        secret: id=npmrc,src=.npmrc
      context: packages/web/builder
      password:
        from_secret: gitea_docker_registry
      tags:
        - latest
    when:
      - event: push
        branch: main

  build-docker-tag:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/luzzle-web-builder
      username: eleith
      dockerfile: packages/web/builder/Dockerfile
      registry: https://git.eleith.com
      context: packages/web/builder
      build_args:
        secret: id=npmrc,src=.npmrc
      password:
        from_secret: gitea_docker_registry
      tags_file: .tags
    when:
      - event: tag

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
