workspace:
  base: /workspace
  path: src

when:
  - event: push
    branch: main
    path:
      include: [".woodpecker/.web-explorer.yml", "packages/web/explorer/**"]
  - event: tag
    ref: "refs/tags/web/v*"

steps:
  prepare:
    image: node:22
    commands:
      - printf '%s' "$LUZZLE_NPMRC" | sed 's/[[:space:]]*$//' >> /root/.npmrc
      - cd packages/web/explorer
      - npm run build:lock
      - npm ci --workspaces=false
    environment:
      LUZZLE_NPMRC:
        from_secret: luzzle_npmrc

  lint:
    image: node:22
    commands:
      - cd packages/web/explorer
      - npm run lint
      - npm run check

  check-version:
    image: node:22
    commands:
      - cd packages/web/explorer
      - |
        VERSION_FROM_PKG=$(npm pkg get version --workspaces=false)

        if [ "\"$VERSION_FROM_TAG\"" != "$VERSION_FROM_PKG" ]; then
          echo "Version mismatch: Git tag version "$VERSION_FROM_TAG" does not match package.json version: $VERSION_FROM_PKG"
          exit 1
        fi
    environment:
     VERSION_FROM_TAG: ${CI_COMMIT_TAG#web/v}
    when:
      - event: tag

  extract-semver-tags:
    image: alpine/git:latest # A small image with git and shell tools
    commands:
      - |
        VERSION_FULL="${CI_COMMIT_TAG#web/v}"
        VERSION_MAJOR=$(echo "$VERSION_FULL" | cut -d. -f1)
        VERSION_MINOR=$(echo "$VERSION_FULL" | cut -d. -f2)

        SEMVER_FULL="$VERSION_FULL"
        SEMVER_MAJOR_MINOR="$VERSION_MAJOR.$VERSION_MINOR"
        SEMVER_MAJOR="$VERSION_MAJOR"

        echo "Extracted versions: Full=$SEMVER_FULL, Major=$SEMVER_MAJOR, Minor=$SEMVER_MINOR"
        echo -e "$SEMVER_FULL\n$SEMVER_MAJOR\n$SEMVER_MINOR" >> .tags
    when:
      - event: tag

  build-docker-main:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/luzzle-explorer
      username: eleith
      dockerfile: packages/web/explorer/Dockerfile
      context: packages/web/explorer
      registry: https://git.eleith.com
      build_args:
        secret: id=npmrc,src=.npmrc
      tags:
        - latest
      password:
        from_secret: gitea_docker_registry
    when:
      - event: push
        branch: main

  build-docker-tag:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: git.eleith.com/eleith.private/luzzle-explorer
      username: eleith
      dockerfile: packages/web/explorer/Dockerfile
      context: packages/web/explorer
      registry: https://git.eleith.com
      build_args:
        secret: id=npmrc,src=.npmrc
      tags_file: .tags
      password:
        from_secret: gitea_docker_registry
    when:
      - event: tag

  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]

  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
