services:
  builder:
    build:
      dockerfile: Dockerfile
      secrets:
        - npmrc
      context: .
    container_name: luzzle-builder
    ports:
      - '9000:9000'
    env_file: .env
    volumes:
      - ../explorer/config.yaml:/app/config.yaml
      - ../explorer/static/pieces/assets:/app/assets
      #- ./archive:/app/archive
      #- ./luzzle.sqlite:/app/data/luzzle.sqlite
      #- ./pre.build.sh:/app/scripts/pre.build.sh
      #- ./post.build.sh:/app/scripts/post.build.sh
    user: 'node'

secrets:
  npmrc:
    file: $HOME/.npmrc
