name: "@luzzle/web.config"

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/config/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/web-config.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter @luzzle/web.config build

      - name: Lint
        run: pnpm --filter @luzzle/web.config lint

      - name: Test
        run: pnpm --filter @luzzle/web.config test
