name: "@luzzle/web.db"

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/db/**'
      - 'packages/web/config/**'
      - 'apps/core/**'
      - '.github/workflows/web-db.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build core + web.config
        run: pnpm --filter @luzzle/core --filter @luzzle/web.config build

      - name: Build
        run: pnpm --filter @luzzle/web.db build

      - name: Lint
        run: pnpm --filter @luzzle/web.db lint

      - name: Test
        run: pnpm --filter @luzzle/web.db test
