name: "@luzzle/web.lsp"

on:
  push:
    branches:
      - main
    tags:
      - '@luzzle/web.lsp@*'
    paths:
      - 'packages/web/lsp/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/web/lsp/**'
      - '.github/workflows/web-lsp.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter @luzzle/web.lsp lint

      - name: Test
        run: pnpm --filter @luzzle/web.lsp test

  build-push:
    needs: check
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check Version
        if: github.ref_type == 'tag'
        run: |
          VERSION_FROM_PKG=$(node -p "require('./packages/web/lsp/package.json').version")
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION_FROM_TAG=${TAG_NAME#@luzzle/web.lsp@}

          if [ "$VERSION_FROM_TAG" != "$VERSION_FROM_PKG" ]; then
            echo "Version mismatch: Tag version $VERSION_FROM_TAG does not match package.json version $VERSION_FROM_PKG"
            exit 1
          fi
          echo "Version $VERSION_FROM_PKG matches."

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/eleith/luzzle-web-lsp
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=match,pattern=@luzzle/web.lsp@(\d+),group=1
            type=match,pattern=@luzzle/web.lsp@(\d+\.\d+),group=1
            type=match,pattern=@luzzle/web.lsp@(\d+\.\d+\.\d+),group=1

      - name: Create dummy npmrc
        run: touch .npmrc

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: packages/web/lsp/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "npmrc=.npmrc"
